// import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import '../model/kategori.dart';

final Map<String, List<Map<String, dynamic>>> TempatByKategori = {
  "Restoran": [
    {
      "subkategori": "Restoran", //nambahin ini supaya kalau untuk di detail ke maps tuh ngirim titik mana aja yg ada di subkategori sehingga bisa muncul titik-titiknya
      "fotoTempat": "galeri/card.png",
      "nama": "Resto Pahlawan",
      "lat": -6.8937,
      "lng": 107.6374,
      "alamat": "Jl. Pahlawan No. 123, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Restoran",
      "fotoTempat": "galeri/card.png",
      "nama": "Resto Cikutra",
      "lat": -6.8940,
      "lng": 107.6378,
      "alamat": "Jl. Cikutra No. 456, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Restoran",
      "fotoTempat": "galeri/card.png",
      "nama": "Resto Sukapura",
      "lat": -6.8935,
      "lng": 107.6370,
      "alamat": "Jl. Sukapura No. 789, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],


  "Kafe": [
    {
      "subkategori": "Kafe",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Cafe Jalan Pahlawan",
      "lat": -6.8938, "lng": 107.6376,
      "alamat": "Jl. Pahlawan No. 111, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Kafe",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Cafe Cikutra",
      "lat": -6.8936, "lng": 107.6372,
      "alamat": "Jl. Cikutra No. 456, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Kafe",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Cafe Sukapura",
      "lat": -6.8941,
      "lng": 107.6375,
      "alamat": "Jl. Sukapura No. 333, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Kafe",
      "fotoTempat": "galeri/bg2.png",
      "nama": "KopiKitaku",
      "lat": -6.89419,
      "lng": 107.63540,
      "alamat": "Jl. Pahlawan No.72, Neglasari, Kec. Cibeunying Kaler, Kota Bandung, Jawa Barat 40123",
      "rating": 5.0,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Pusat Perbelanjaan": [
    {
      "subkategori": "Pusat Perbelanjaan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Mall BEC",
      "lat": -6.90767,
      "lng": 107.60880,
      "alamat": "Jl. BEC No. 1, Bandung",
      "rating": 4.6,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Pusat Perbelanjaan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Mall BIP",
      "lat": -6.90843,
      "lng": 107.61084,
      "alamat": "Jl. Cikutra No. 456, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Pusat Perbelanjaan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "DBotanica Bandung Mall",
      "lat": -6.89297,
      "lng": 107.58518,
      "alamat": "Jl. Botanica No. 3, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Kecantikan": [
    {
      "subkategori": "Kecantikan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "My Beauty Nail Art Bandung",
      "lat": -6.89388,
      "lng": 107.63825, ""
        "alamat": "Jl. Beauty No. 1, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Kecantikan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Puspitararas Salon & Spa",
      "lat": -6.90014,
      "lng": 107.63699,
      "alamat": "Jl. Salon No. 2, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Kecantikan",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Rosellia.MSA",
      "lat": -6.89882,
      "lng": 107.63697,
      "alamat": "Jl. Rose No. 3, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Hiburan Keluarga": [
    {
      "subkategori": "Hiburan Keluarga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Museum Geologi Bandung",
      "lat": -6.90045,
      "lng": 107.62140,
      "alamat": "Jl. Diponegoro No. 57, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Hiburan Keluarga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Taman Makam Pahlawan Nasional Cikutra",
      "lat": -6.89217,
      "lng": 107.63558,
      "alamat": " 4J5P+26M, Neglasari, Kec. Cibeunying Kaler, Kota Bandung, Jawa Barat 40191",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Hiburan Keluarga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Alun-alun Kota Bandung", ""
        "lat": -6.92158,
      "lng": 107.60716,
      "alamat": "Jl. Asia Afrika, Bandung",
      "rating": 4.0,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Tempat Olahraga": [
    {
      "subkategori": "Tempat Olahraga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Ksatria Gym",
      "lat": -6.89551,
      "lng": 107.63826,
      "alamat": "Jl. Ksatria No. 1, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Tempat Olahraga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "GOR C-Tra Arena",
      "lat": -6.89305,
      "lng": 107.64016,
      "alamat": "Jl. C-Tra No. 2, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Tempat Olahraga",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Lapangan Gasibu",
      "lat": -6.90012,
      "lng": 107.61876,
      "alamat": "Jl. Gasibu, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Akomodasi": [
    {
      "subkategori": "Akomodasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Hotel Augusta Surapati Bandung",
      "lat": -6.89736,
      "lng": 107.63378,
      "alamat": "Jl. Surapati No. 1, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Akomodasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Hotel Saidah Guest House",
      "lat": -6.89707,
      "lng": 107.63889,
      "alamat": "Jl. Saidah No. 2, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Akomodasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Kost Gloria",
      "lat": -6.89270,
      "lng": 107.63505,
      "alamat": "Jl. Gloria No. 3, Bandung",
      "rating": 4.0,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Transportasi": [
    {
      "subkategori": "Transportasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Stasiun Bandung",
      "lat": -6.91352,
      "lng": 107.60076,
      "alamat": "Jl. Kebon Kawung No. 1, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Transportasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Halte Jl.Pahlawan",
      "lat": -6.89300,
      "lng": 107.63533,
      "alamat": "Jl. Pahlawan, Bandung",
      "rating": 3.8,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Transportasi",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Terminal Cicaheum",
      "lat": -6.90235,
      "lng": 107.65672,
      "alamat": "Jl. A.H. Nasution, Bandung",
      "rating": 3.9,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "SD": [
    {
      "subkategori": "SD",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SDN 025 Cikutra",
      "lat": -6.89319,
      "lng": 107.63728,
      "alamat": "Jl. Cikutra No. 25, Bandung",
      "rating": 4.0,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SD",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SDN Cikutra 2",
      "lat": -6.89325,
      "lng": 107.63711,
      "alamat": "Jl. Cikutra No. 26, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SD",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SDN 114 Bojongkoneng",
      "lat": -6.89251,
      "lng": 107.64476,
      "alamat": "Jl. Bojongkoneng No. 114, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "SMP": [
    {
      "subkategori": "SMP",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMP Istiqamah Pahlawan",
      "lat": -6.89591,
      "lng": 107.63410,
      "alamat": "Jl. Pahlawan No. 91, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SMP",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMP PGII 2 Bandung",
      "lat": -6.90043,
      "lng": 107.636360,
      "alamat": "Jl. PGII No. 2, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SMP",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMP 8 Pasundan",
      "lat": -6.89510,
      "lng": 107.64210,
      "alamat": "Jl. Pasundan No. 8, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "SMA": [
    {
      "subkategori": "SMA",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMA Islam Cendikia Muda Bandung",
      "lat": -6.89454,
      "lng": 107.63457,
      "alamat": "Jl. Cendikia No. 1, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SMA",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMA Pribadi Bandung",
      "lat": -6.89897,
      "lng": 107.64074,
      "alamat": "Jl. Pribadi No. 1, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "SMA",
      "fotoTempat": "galeri/bg2.png",
      "nama": "SMK 4 Pasundan",
      "lat": -6.89503,
      "lng": 107.64220,
      "alamat": "Jl. Pasundan No. 4, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Universitas": [
    {
      "subkategori": "Universitas",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Universitas Winaya Mukti Pahlawan",
      "lat": -6.89269,
      "lng": 107.63461,
      "alamat":
      "Jl. Pahlawan No. 269, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Universitas",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Institut Teknologi Nasional Bandung (ITENAS)",
      "lat": -6.89788,
      "lng": 107.63569,
      "alamat": "Jl. PKH. Hasan Mustapa No. 23, Bandung",
      "rating": 4.6,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Universitas",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Universitas Widyatama",
      "lat": -6.89779, "lng": 107.64549,
      "alamat": "Jl. Cikutra No. 204A, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Rumah Sakit": [
    {
      "subkategori": "Rumah Sakit",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Rumah Sakit Kartini Bandung",
      "lat": -6.89716,
      "lng": 107.63463,
      "alamat": "Jl. Kartini No. 1, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Rumah Sakit",
      "fotoTempat": "galeri/bg2.png",
      "nama": "RS Kenangan",
      "lat": -6.89990,
      "lng": 107.64320,
      "alamat": "Jl. Kenangan No. 2, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Rumah Sakit",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Klinik Amanah Suci",
      "lat": -6.90038,
      "lng": 107.64534,
      "alamat": "Jl. Amanah No. 3, Bandung",
      "rating": 4.0,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Apotek": [
    {
      "subkategori": "Apotek",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Apotek Pahlawan Bandung",
      "lat": -6.89489,
      "lng": 107.63511,
      "alamat": "Jl. Pahlawan No. 489, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Apotek",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Apotek Adora Cikutra",
      "lat": -6.89219,
      "lng": 107.63424,
      "alamat": "Jl. Cikutra No. 219, Bandung",
      "rating": 4.1,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Apotek",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Apotek Heka Bandung",
      "lat": -6.89780,
      "lng": 107.63688,
      "alamat": "Jl. Heka No. 780, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],



  "Tempat Ibadah": [
    {
      "subkategori": "Tempat Ibadah",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Masjid Jami Al Huda RW 02 Cikutra",
      "lat": -6.89217,
      "lng": 107.63755,
      "alamat": "Jl. Cikutra RW 02, Bandung",
      "rating": 4.5,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Tempat Ibadah",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Masjid Al Fattah",
      "lat": -6.88890,
      "lng": 107.63717,
      "alamat": "Jl. Al Fattah No. 890, Bandung",
      "rating": 4.3,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Tempat Ibadah",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Masjid Ash Shofa",
      "lat": -6.89384,
      "lng": 107.63854,
      "alamat": "Jl. Ash Shofa No. 384, Bandung",
      "rating": 4.4,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
    {
      "subkategori": "Tempat Ibadah",
      "fotoTempat": "galeri/bg2.png",
      "nama": "Gereja Bathel Tabernakel Cisokan",
      "lat": -6.90165,
      "lng": 107.63188,
      "alamat": "Jl. Cisokan No. 165, Bandung",
      "rating": 4.2,
      "jamOperasi": "9.00 AM - 8.30 PM",
      "kontak": "0812-2456-7890",
      "fotoMenu": [
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
        {"namaMenu": "Ayama Gulai", "gambarMenu": "galeri/ayamgulai.jpeg"},
        {"namaMenu": "Nasi Gulai", "gambarMenu": "galeri/nasigulai.jpeg"},
      ],
      "fasilitas": [
        {"namafas": "Wifi Gratis", "icon": Icons.wifi},
        {"namafas": "Area Parkir", "icon": Icons.local_parking},
        {"namafas": "AC", "icon": Icons.ac_unit},
        {"namafas": "Prasmanan", "icon": Icons.restaurant_menu},
        {"namafas": "Ruang Nyaman", "icon": Icons.room_preferences_outlined},
      ],
      "gambar": [
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
        {"gambar": "galeri/ayamgulai.jpeg"},
        {"gambar": "galeri/nasigulai.jpeg"},
      ],
    },
  ],
};